version:2.1
jobs:
  build:
  working_directory: ~/repo
    docker:
      - image: node:14-alpine3.13
      - image: circleci/postgres:14-alpine-ram
      environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hermes_db
    - image: postgres:12



steps:
- checkout

# Download cache dependencies
- restore_cache:
  keys:
  - v1-depencies-{{ checksum "package.json" }}
 # Use latest cacheif no exact match is found
  - v1-dependencies 


- run: npm install

# run tests!
- run: npm run test

- setup_remote_docker:
docker_layer_caching: true

