version: 2.1
orbs:
  node: circleci/node@3.0.0
jobs:
  build_and_test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-pakages
      -run:
        command: npm run test
workflows: 
  build_and_test:
    jobs:
      -build-and-test